import type { LucideIcon } from "lucide-react-native";
import {
  Activity,
  Apple,
  Armchair,
  Axe,
  BookOpen,
  Briefcase,
  Bug,
  Building2,
  Cake,
  Camera,
  Car,
  CarFront,
  CircleDot,
  CookingPot,
  Disc3,
  Droplets,
  Dumbbell,
  GlassWater,
  Hammer,
  Hand,
  HardHat,
  Heart,
  Key,
  Languages,
  Layers,
  LayoutGrid,
  Monitor,
  Music,
  Navigation,
  Paintbrush,
  Palette,
  PartyPopper,
  Ruler,
  Scissors,
  Shield,
  Smartphone,
  Sparkles,
  SprayCan,
  Stethoscope,
  TreePine,
  Tv,
  Umbrella,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react-native";

export const categoryIconMap: Record<string, LucideIcon> = {
  eletricista: Zap,
  encanador: Droplets,
  pintor: Paintbrush,
  diarista: Sparkles,
  pedreiro: HardHat,
  marceneiro: Ruler,
  jardineiro: TreePine,
  mecanico: Car,
  cabeleireira: Scissors,
  fotografo: Camera,
  "personal-trainer": Dumbbell,
  "tecnico-informatica": Monitor,
  telhadista: Umbrella,
  vidraceiro: GlassWater,
  serralheiro: Shield,
  gesseiro: Layers,
  "instalador-ar": Wind,
  "instalador-antena": Tv,
  "instalador-cameras": Camera,
  "instalador-internet": Wifi,
  desentupidora: SprayCan,
  dedetizadora: Bug,
  "limpeza-piscina": Waves,
  chaveiro: Key,
  tapeceiro: Armchair,
  "montador-moveis": Wrench,
  "assistente-tecnica-celular": Smartphone,
  "lavagem-carro": CircleDot,
  manicure: Hand,
  designer: Palette,
  "professor-particular": BookOpen,
  "aula-musica": Music,
  "aula-idiomas": Languages,
  "motorista-particular": Navigation,
  cozinheiro: CookingPot,
  confeiteiro: Cake,
  buffet: UtensilsCrossed,
  sommelier: Wine,
  dj: Disc3,
  "aluguel-carro": CarFront,
  animador: PartyPopper,
  nutricionista: Apple,
  psicologo: Heart,
  medico: Stethoscope,
  fisioterapeuta: Activity,
  carpinteiro: Hammer,
  paisagista: Axe,
  incorporadora: Building2,
};

export function getCategoryIcon(slug: string): LucideIcon {
  return categoryIconMap[slug] ?? Briefcase;
}
